# Generated by Django 2.0.6 on 2018-07-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_student'),
    ]

    operations = [
    ]
