# Generated by Django 2.0.6 on 2018-07-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180720_1728'),
    ]

    operations = [
    ]
