# Generated by Django 2.0.6 on 2018-07-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180722_1346'),
    ]

    operations = [
    ]
