# Generated by Django 2.0.6 on 2018-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180722_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
            options={
                'verbose_name': '前台用户管理',
                'db_table': 'user',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生信息'},
        ),
    ]
