# Generated by Django 2.0.6 on 2018-07-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180722_1444'),
    ]

    operations = [
    ]
