# Generated by Django 2.0.6 on 2018-07-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180725_1818'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
    ]
