# Generated by Django 2.0.6 on 2018-07-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180725_1818'),
    ]

    operations = [
    ]
